import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';
import { loadEnv } from 'vite';

const FCM_VERSION = '12.11.0';

/**
 * Writes `public/firebase-messaging-sw.js` from Vite env so background FCM matches the web app config.
 */
export function fcmServiceWorkerPlugin(): Plugin {
  return {
    name: 'fcm-service-worker',
    configResolved(config) {
      const env = loadEnv(config.mode, config.root, '');
      writeSw(config.root, {
        VITE_FIREBASE_API_KEY: env.VITE_FIREBASE_API_KEY || '',
        VITE_FIREBASE_AUTH_DOMAIN: env.VITE_FIREBASE_AUTH_DOMAIN || '',
        VITE_FIREBASE_PROJECT_ID: env.VITE_FIREBASE_PROJECT_ID || '',
        VITE_FIREBASE_STORAGE_BUCKET: env.VITE_FIREBASE_STORAGE_BUCKET || '',
        VITE_FIREBASE_MESSAGING_SENDER_ID: env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
        VITE_FIREBASE_APP_ID: env.VITE_FIREBASE_APP_ID || '',
      });
    },
  };
}

function writeSw(root: string, env: Record<string, string>) {
  const publicDir = path.join(root, 'public');
  if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
  const outFile = path.join(publicDir, 'firebase-messaging-sw.js');

  const config = {
    apiKey: env.VITE_FIREBASE_API_KEY || '',
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || '',
    projectId: env.VITE_FIREBASE_PROJECT_ID || '',
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: env.VITE_FIREBASE_APP_ID || '',
  };

  if (!config.apiKey || !config.projectId) {
    const stub = `// Generated by Vite — set VITE_FIREBASE_* in .env (and VITE_FIREBASE_VAPID_KEY for push), then restart.\nself.addEventListener('install', (e) => self.skipWaiting());\n`;
    fs.writeFileSync(outFile, stub, 'utf8');
    return;
  }

  const js = `importScripts('https://www.gstatic.com/firebasejs/${FCM_VERSION}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FCM_VERSION}/firebase-messaging-compat.js');
firebase.initializeApp(${JSON.stringify(config)});
const messaging = firebase.messaging();
messaging.onBackgroundMessage((payload) => {
  const title = payload.notification && payload.notification.title
    ? payload.notification.title
    : 'Hearing Hope';
  const options = {
    body: (payload.notification && payload.notification.body) || '',
    icon: '/manifest-icon-192.maskable.png',
    badge: '/manifest-icon-192.maskable.png',
    data: payload.data || {},
  };
  return self.registration.showNotification(title, options);
});
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || '/app';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url && 'focus' in client) return client.focus();
      }
      if (self.clients.openWindow) return self.clients.openWindow(url);
    })
  );
});
`;
  fs.writeFileSync(outFile, js, 'utf8');
}
